version: '3.8'

services:
  # Neon Local proxy service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - acquisitions-network

  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reloading in development
      - .:/app
      - /app/node_modules
      # Mount logs directory
      - ./logs:/app/logs
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Database migration service
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-migrate-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://neon:npg@neon-local:5432/neondb?sslmode=require
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-network
    command: ["npm", "run", "db:migrate"]
    profiles:
      - migration

networks:
  acquisitions-network:
    driver: bridge

volumes:
  logs:
    driver: local